# Generated by Django 4.2.11 on 2025-12-24 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название города')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-идентификатор')),
                ('avg_price_per_sqm', models.DecimalField(decimal_places=2, help_text='Средняя рыночная цена за квадратный метр', max_digits=10, verbose_name='Средняя цена за м² (руб.)')),
                ('population', models.IntegerField(blank=True, help_text='Примерная численность населения', null=True, verbose_name='Население')),
                ('description', models.TextField(blank=True, help_text='Краткое описание города, районов, инфраструктуры', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Улица, дом, корпус', max_length=255, verbose_name='Адрес')),
                ('area', models.DecimalField(decimal_places=2, help_text='Общая площадь квартиры', max_digits=6, verbose_name='Площадь (м²)')),
                ('rooms', models.IntegerField(choices=[(1, '1-к'), (2, '2-к'), (3, '3-к'), (4, '4-к'), (5, '5-к')], default=1, verbose_name='Количество комнат')),
                ('floor', models.IntegerField(help_text='На каком этаже находится квартира', verbose_name='Этаж')),
                ('total_floors', models.IntegerField(help_text='Общее количество этажей в здании', verbose_name='Всего этажей в доме')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Балкон/лоджия')),
                ('repair_type', models.CharField(choices=[('без ремонта', 'Без ремонта'), ('косметический', 'Косметический'), ('евро', 'Евроремонт'), ('дизайнерский', 'Дизайнерский')], default='косметический', max_length=20, verbose_name='Тип ремонта')),
                ('description', models.TextField(blank=True, help_text='Дополнительные особенности квартиры', verbose_name='Дополнительное описание')),
                ('desired_price', models.DecimalField(decimal_places=2, help_text='Цена, которую вы хотели бы получать', max_digits=10, verbose_name='Желаемая цена аренды (руб./мес.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='analyzer.city', verbose_name='Город')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fair_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Справедливая цена (руб./мес.)')),
                ('price_difference', models.DecimalField(decimal_places=2, help_text='Отрицательное - цена завышена, положительное - занижена', max_digits=10, verbose_name='Разница с желаемой ценой')),
                ('similar_offers_count', models.IntegerField(verbose_name='Количество похожих предложений')),
                ('avg_price_per_sqm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя цена за м²')),
                ('median_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Медианная цена')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная цена')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимальная цена')),
                ('recommendation', models.TextField(help_text='Текстовая рекомендация по ценообразованию', verbose_name='Рекомендация')),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='analysis_charts/', verbose_name='График анализа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отчета')),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_report', to='analyzer.apartment', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Отчет анализа',
                'verbose_name_plural': 'Отчеты анализа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('avito', 'Avito'), ('cian', 'ЦИАН'), ('yandex', 'Яндекс.Недвижимость'), ('mock', 'Тестовые данные')], default='mock', max_length=20, verbose_name='Источник данных')),
                ('external_id', models.CharField(blank=True, help_text='Идентификатор в исходной системе', max_length=100, verbose_name='Внешний ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Площадь (м²)')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена аренды (руб./мес.)')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на объявление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('parsed_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения данных')),
                ('additional_info', models.JSONField(blank=True, help_text='Дополнительные параметры в JSON формате', null=True, verbose_name='Дополнительная информация')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_offers', to='analyzer.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Рыночное предложение',
                'verbose_name_plural': 'Рыночные предложения',
                'ordering': ['-parsed_date'],
                'indexes': [models.Index(fields=['city', 'rooms', 'area'], name='analyzer_ma_city_id_55ec12_idx'), models.Index(fields=['price'], name='analyzer_ma_price_a80419_idx'), models.Index(fields=['is_active'], name='analyzer_ma_is_acti_35d93b_idx')],
            },
        ),
    ]
