# Generated by Django 4.2.11 on 2025-12-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая широта (автоматически заполняется)', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая долгота (автоматически заполняется)', max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
