# Generated by Django 4.2.11 on 2025-12-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_apartment_latitude_apartment_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketoffer',
            name='floor',
            field=models.IntegerField(blank=True, help_text='На каком этаже находится квартира', null=True, verbose_name='Этаж'),
        ),
    ]
