# Generated by Django 4.2.11 on 2025-12-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_marketoffer_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая широта центра города', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая долгота центра города', max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
