# Generated by Django 4.2.11 on 2025-12-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketoffer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая широта', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='marketoffer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Географическая долгота', max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
