# Generated by Django 4.2.11 on 2025-12-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_marketoffer_latitude_marketoffer_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='URL-идентификатор'),
        ),
    ]
