# Generated by Django 4.2.11 on 2025-12-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_alter_city_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisreport',
            options={},
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средняя цена'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_report', to='analyzer.apartment'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='avg_price_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средняя цена за м²'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='analysis_charts/', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='fair_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Справедливая цена'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Максимальная цена'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='median_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Медианная цена'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='price_difference',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Разница в процентах'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='recommendation',
            field=models.TextField(verbose_name='Рекомендация'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='similar_offers_count',
            field=models.IntegerField(default=0, verbose_name='Количество похожих предложений'),
        ),
    ]
