# Generated by Django 4.2.11 on 2025-12-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_alter_analysisreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='chart_image_data',
            field=models.TextField(blank=True, null=True, verbose_name='График (base64)'),
        ),
    ]
