# Generated by Django 4.2.11 on 2025-12-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_analysisreport_chart_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisreport',
            name='chart_image_data',
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='chart_image_base64',
            field=models.TextField(blank=True, null=True, verbose_name='График в формате base64'),
        ),
    ]
